### ISSUE TITLE
Obstacle avoidance with Kinect

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/scitos_2d_navigation#14]
This came out of the MAPS breakout group at the GA
- [x] test the short range Kinect (Nils)
- [x] find a good way to mount the Kinect (either a "neck lace" or using the two screws at the neck) (no idea why this is upside down on github...)
  ![img_20131004_113310](https://f.cloud.github.com/assets/1153084/1268498/7e6b5470-2ce0-11e3-9960-74fa8d24c283.jpg)
- [x] implement obstacle avoidance using off-the-shelf components to generate  a suitable costmap

**Comment by nilsbore** [comment]
I think we can close this issue now since camera, mounting and implementation are decided upon. The problems that turn up can be discussed in separate issues.
