### ISSUE TITLE
stairs

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/scitos_2d_navigation#18]
We are just testing our robot in the marathon environment for the first time. Here we have to deal with some fancy stairs where the robot gets stuck (see pictures). The problem is that there is nothing to bump into, so the robot will just go on sending out motor commands. 

I edited the map by drawing a black line where there are "No-Go" areas for the robot. As it sometimes goes there anyway, is there any other remedy? 

![photo](https://f.cloud.github.com/assets/4250227/1493662/3f8c4be6-47d0-11e3-95ac-bf6394c3fefc.JPG)

![error_stairs](https://f.cloud.github.com/assets/4250227/1493681/7ff3e018-47d0-11e3-8212-42cd57e03736.png)

**Comment by nilsbore** [comment]
This will have to be fixed by the 3d obstacle avoidance. So you'll have to wait for the mounting and primesense!

**Comment by mzillich** [comment]
We have the primesense carmine sensor and ordered the mounting. Can we simply sticky-tape the carmine to the robot for now and try it out?

**Comment by hawesie** [comment]
Provided you can get the correct transform in the taped pose, then it should be fine. @nilsbore is the expert here though.

**Comment by nilsbore** [comment]
As long as you keep it looking straight forward (downwards) and lower than 1.2 meters it should be ok. Just be sure to have the datacenter running, run the calibrate_chest node and then have the datacenter running every time you start up the robot. Make sure that the largest plane that the chest camera sees is the floor when you run the calibration node.

**Comment by mzillich** [comment]
Ok, cool. Just to be sure: we only need to run the calibrate_chest node once right?

**Comment by nilsbore** [comment]
Yes, as long as you don't mess with the camera fixture.

**Comment by hawesie** [comment]
Are these instructions on a wiki/README somewhere?

**Comment by nilsbore** [comment]
Oh, no, forgot to add them after I merged, will do!

**Comment by nilsbore** [comment]
Was this fixed by using the chest camera, @ToMadoRe ?

**Comment by ToMadoRe** [comment]
Yes, problem fixed by the chest cam.
