### ISSUE TITLE
chest_xtion topic

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/scitos_2d_navigation#19]
Did you modify something in the bringup launch file as well to start the chest camera? I don't have any topics \chest_xtion (only \head_xtion).
Can you plug in both xtion cameras and get the topics? We don't really mind to unplug the head one for the marathon.

**Comment by nilsbore** [comment]
Yes, I had to modify the launch file. @RaresAmbrus will open a pull request after lunch which will enable running with two cameras. In the meantime, just have only the chest camera plugged in and change the topic in the launch file.

**Comment by ToMadoRe** [comment]
Alright thanks. And what kind of openni version do you use? I still cannot subscribe to RGB and depth at the same time. But that shouldn't matter for this, right?

**Comment by nilsbore** [comment]
No it shouldn't matter. You can try uncommenting ;USBInterface=2(or similar) in /etc/openni/GlobalDefaults.ini if you haven't done that. But Rares' pull request will take care of this.

**Comment by RaresAmbrus** [comment]
@ToMadoRe 
I've merged my changes in scitos_robot. Do an update and then follow the instructions on the scitos_robot wiki (bottom of the page). You will have to fiddle a bit with the USB connections - right now we have one camera on USB3 and the other one on USB2. I suggest restarting the robot after plugging in the cameras.

**Comment by nilsbore** [comment]
Closing this since this is fixed by https://github.com/strands-project/scitos_robot/pull/24.
