### ISSUE TITLE
Height of obstacles from chest sensor

### ISSUE THREAD

**Issue by hawesie** [strands-project/scitos_2d_navigation#21]
@nilsbore said he would provide instructions on how to adjust the height at which objects from the chest sensor are filtered out (in order to allow TUW @mzillich to see window frames).

**Comment by nilsbore** [comment]
Change the line `point_cloud_sensor: {topic: /move_base/points_obstacle, data_type: PointCloud2, marking: true, clearing: false, min_obstacle_height: 0.1, max_obstacle_height: 0.9, observation_persistence: 0.0, obstacle_range: 2.0}` in scitos_move_base_params_3d/costmap_common_params.yaml to the `min_obstacle_height` that you want. I don't know how to make that a ros parameter so you will have to change it in the file for now.

**Comment by hawesie** [comment]
Thanks! @mzillich please can you report when you've got a reliable low value?

**Comment by nilsbore** [comment]
@hawesie There is a parameter to `strands_movebase` now. Please close.
