### ISSUE TITLE
Unable to test scitos_2d_navigation atm

### ISSUE THREAD

**Issue by nilsbore** [strands-project/scitos_2d_navigation#25]
So we haven't had a functioning robot for over a week now and I've been unable to work as much on this package as planned. If one or more could test this some more and investigate for example a different robot footprint(https://github.com/strands-project/scitos_2d_navigation/issues/22) that would be great. Also @ToMadoRe seems to have had some problems with people moving in front of the robot(https://github.com/strands-project/scitos_2d_navigation/issues/20), something that I was unable to get to happen after the later commits.

I will get something running with a PrimeSense so I can at least see what happens when the camera is static(to look at Tomas' problem) but we will need to test on the robots. I would really like if people could get the cameras up and running as soon as possible and try to identify the cause of any issues that arise(you can use an xtion if you don't have the primesense). I am always available for questions, for example via skype(nils.bore). That way I can try to devise patches and send them back to see if that solves the problem.

**Comment by ToMadoRe** [comment]
Also, please let me know if anyone else is having problems with starting the robot with two cameras. 
By trial and error, I figured out that I have to plug in the head camera into USB3.0 just after the GRUB menu disappeared. A bit later, the camera won't be recognized by the system or, otherwise, the screen stays black and shows a blinking cursor.

**Comment by nilsbore** [comment]
Did you manage to get them running at a steady rate?

**Comment by ToMadoRe** [comment]
I actually don't think it runs on a steady rate. I only checked the images in RVIZ, which sometimes lag a bit. But apart from that, I haven't really investigated that.

**Comment by RaresAmbrus** [comment]
You should check with rostopic hz.

**Comment by ToMadoRe** [comment]
okay, will do that next time I start the robot.

**Comment by RaresAmbrus** [comment]
When running only scitos bringup you should ideally get an update rate of 29-30 hz for all the streams, rgb and depth.
