### ISSUE TITLE
refactoring and preparing release

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/scitos_2d_navigation#43]
This repository needs a little restructuring according to the plans outlined in https://github.com/strands-project/strands_management/wiki/software-distribution

The idea is that it is pure configuration repository with launch files and parameter files that is specific to the scitos robot. So, it should only contain parameters and launch files for `move_base` on scitos, everyting else (src, and 3D stuff) to be moved to new repo `strands_movebase` without scitos prefix (use strands only if needed). 

Once this is complete, the repository's dependencies should be checked and it should be released as outlined in https://github.com/strands-project/strands_management/wiki/STRANDS-release-procedures

**Comment by nilsbore** [comment]
So configuration files and launch files for 3d move_base should also go in the strands_movebase repo? Or should scitos_2d_navigation depend on strands_movebase? Also, I think it looks good to put the calibrate_chest in the strands_movebase repo. But the `chest_calibration_publisher` should always be run at robot startup (otherwise we don't have a valid tf) so `scitos.launch` would still have to include it.

**Comment by marc-hanheide** [comment]
I think the plan is that `scitos_2d_navigation` is only about the parameters for having a **2D** navigation without any Kinect etc. So, also the launch file including the `chest_calibration_publisher` should go into `strands_movebase`. This one should in @hawesie and my view only have stuff in it to run move_base on a scitos robot. The other stuff are our own extensions if that makes sense?

**Comment by nilsbore** [comment]
Yeah, I think it does, thanks for clarifying.

**Comment by nilsbore** [comment]
@hawesie , @marc-hanheide Could one of you guys create the repo and I'll do it in the next few days.

**Comment by marc-hanheide** [comment]
done: https://github.com/strands-project/strands_movebase

you're also a member with write access, @nilsbore

**Comment by nilsbore** [comment]
Thanks!

**Comment by nilsbore** [comment]
Are we still supposed to work on the hydro-devel branch?

**Comment by marc-hanheide** [comment]
I'd say so, yes!

**Comment by marc-hanheide** [comment]
I have already entered this repo into the integration server, but not released anything (obviously). Most importantly, this package doesn't install anything yet. the `install` targets in `CMakeLists.txt` need to be filled properly.

**Comment by marc-hanheide** [comment]
I should add that the package builds fine on the integration server, so all dependencies are correctly resolved. Well done!

See https://lcas.lincoln.ac.uk/jenkins/job/devel-hydro-scitos_2d_navigation/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/1/console

**Comment by nilsbore** [comment]
@marc-hanheide Close this?

**Comment by marc-hanheide** [comment]
sure
