### ISSUE TITLE
Amcl uses the no go map to localise

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/scitos_2d_navigation#44]
Acml currently calls the /static_map service to get the map and that delivers the nogomap rather than the correct Nav map due to the order in the scitos_2d_navigation launch file. We should set amcl to use the /map topic instead with private parameter `use_map_topic`. 

This is an urgent matter as it causes major localisation issues when using a highly crafted nogomap.

**Comment by marc-hanheide** [comment]
@Jailander is this fixed now?

**Comment by Jailander** [comment]
yes it is, I tested it on simulation doesn't happen any more

**Comment by marc-hanheide** [comment]
then let's close this

**Comment by marc-hanheide** [comment]
ah. not merged yet... then I shall reopen

**Comment by Jailander** [comment]
Now is merged you can close this issue
